import sys
import json
import yaml
import os
from datetime import datetime


def load_category_config(category_key):
    with open(f"config/categories/{category_key}.yaml") as f:
        return yaml.safe_load(f)


def status_icon(status):
    return {"Met": "PASS", "Not Met": "FAIL", "Needs Review": "REVIEW"}.get(status, "?")


def build_report(extracted, verification, config, category_key):
    website_items = {item["id"]: item for item in config["checklist"] if item["verifiable"] == "website"}
    internal_items = [item for item in config["checklist"] if item["verifiable"] == "internal"]

    review_date = datetime.now().strftime("%Y-%m-%d %H:%M")

    lines = []
    lines.append(f"# Pre-Approval Verification Report - {config['display_name']}")
    lines.append("")
    lines.append(f"**Review date:** {review_date}")
    lines.append("")

    lines.append("## Request at a Glance")
    lines.append("")
    lines.append(f"- **Participant:** {extracted.get('participant_name', 'N/A')}")
    lines.append(f"- **Provider/Vendor:** {extracted.get('provider_name', 'N/A')}")
    item_field = next((f for f in ["class_name", "course_name", "item_name", "organization_name", "program_name"] if f in extracted), None)
    if item_field:
        lines.append(f"- **Requested item/class/service:** {extracted.get(item_field)}")
    lines.append(f"- **Website/link:** {verification.get('url', 'N/A')}")
    lines.append(f"- **Category:** {config['display_name']}")
    lines.append(f"- **Capture date/time:** {verification.get('capture_timestamp', 'N/A')}")
    lines.append("")

    lines.append("## Rate Comparison")
    lines.append("")
    fee_field = next((f for f in ["fee_per_session", "fee_per_class", "membership_fee", "item_price", "fee_per_course", "fee"] if f in extracted), None)
    form_fee = extracted.get(fee_field, "Not stated on form") if fee_field else "Not stated on form"

    fee_match_result = next((r for r in verification["verification_results"] if r["id"] == "fee_match"), None)
    if fee_match_result:
        verdict = fee_match_result["status"]
        note = fee_match_result["note"]
    else:
        verdict = "Needs Review"
        note = "No fee-match check was run for this category."

    lines.append(f"- **Rate on application:** {form_fee}")
    rate_note = fee_match_result["note"] if fee_match_result else "Not checked"
    lines.append(f"- **Rate found on website:** {rate_note}")
    lines.append(f"- **Verdict:** {status_icon(verdict)} {verdict} - {note}")
    lines.append("")

    lines.append("## Per-Criterion Findings (Website-Verifiable)")
    lines.append("")
    lines.append("| Criterion | Status | Evidence | Note |")
    lines.append("|---|---|---|---|")
    for result in verification["verification_results"]:
        item = website_items.get(result["id"], {})
        label = item.get("label", result["id"])
        status = result["status"]
        icon = status_icon(status)
        evidence = result.get("evidence_screenshot") or "-"
        note = result["note"]
        lines.append(f"| {label} | {icon} {status} | {evidence} | {note} |")
    lines.append("")

    lines.append("## Items Not Verifiable Online (Internal - For Reviewer)")
    lines.append("")
    if internal_items:
        for item in internal_items:
            note = f" _{item['note']}_" if "note" in item else ""
            lines.append(f"- **{item['label']}** - Internal / not website-verifiable.{note}")
    else:
        lines.append("_None for this category._")
    lines.append("")

    lines.append("## Evidence Captures")
    lines.append("")
    lines.append(f"**Whole-page capture:** `{verification.get('full_page_screenshot', 'N/A')}`")
    lines.append("")
    lines.append("**Targeted captures (per confirmed item):**")
    lines.append("")
    for result in verification["verification_results"]:
        if result.get("evidence_screenshot"):
            item = website_items.get(result["id"], {})
            label = item.get("label", result["id"])
            lines.append(f"- **{label}:** `{result['evidence_screenshot']}`")
    lines.append("")

    lines.append("---")
    lines.append("_This report was generated by an AI-assisted verification tool. It does not constitute an approval or denial decision. A human Pre-Approvals Reviewer must review this report and make the final determination._")

    return "\n".join(lines)


def main():
    if len(sys.argv) < 4:
        print("Usage: python3 src/generate_report.py <extracted_json_path> <verification_json_path> <category_key>")
        sys.exit(1)

    extracted_path = sys.argv[1]
    verification_path = sys.argv[2]
    category_key = sys.argv[3]

    with open(extracted_path) as f:
        extracted = json.load(f)
    with open(verification_path) as f:
        verification = json.load(f)

    config = load_category_config(category_key)
    report_md = build_report(extracted, verification, config, category_key)

    os.makedirs("output/reports", exist_ok=True)
    participant = extracted.get("participant_name", "unknown").replace(" ", "_").replace(".", "")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_path = f"output/reports/report_{participant}_{timestamp}.md"

    with open(report_path, "w") as f:
        f.write(report_md)

    print(f"Report saved to: {report_path}")
    print("")
    print(report_md)


if __name__ == "__main__":
    main()
